[ default ]
domain                  = freyjapki.com
rootca                  = FreyjaPKIRootCA 
signingca               = FreyjaPKISigningCA
dir                     = .              
pki_url                 = http://pki.$domain
aia_url                 = $pki_url/$rootca.cer
crl_url                 = $pki_url/$rootca.crl     
name_opt                = ca_default

# CA certificate request

[ req ]
default_bits            = 2048                  
encrypt_key             = no                  
default_md              = sha256              
utf8                    = yes                
string_mask             = utf8only          
prompt                  = no               
distinguished_name      = ca_dn           
req_extensions          = ca_reqext      

[ ca_dn ]
commonName              = $rootca

[ ca_reqext ]
keyUsage                = critical,keyCertSign,cRLSign
basicConstraints        = critical,CA:true
subjectKeyIdentifier    = hash

# CA operational settings

[ ca ]
default_ca              = root_ca               

[ root_ca ]
certificate             = $dir/$rootca/$rootca.pem  
private_key             = $dir/$rootca/private/$rootca.key  
new_certs_dir           = $dir/$rootca/certs           
serial                  = $dir/$rootca/db/$rootca.crt.srl 
crlnumber               = $dir/$rootca/db/$rootca.crl.srl
database                = $dir/$rootca/db/$rootca.db 
unique_subject          = no                   
default_days            = 3653                 
default_md              = sha256               
policy                  = any_pol              
email_in_dn             = no                   
preserve                = no                   
name_opt                = $name_opt            
cert_opt                = ca_default           
copy_extensions         = copy                 
x509_extensions         = signing_ca_ext       
default_crl_days        = 3652                 

[ any_pol ]
domainComponent         = optional
countryName             = optional
stateOrProvinceName     = optional
localityName            = optional
organizationName        = optional
organizationalUnitName  = optional
commonName              = optional
emailAddress            = optional


[ root_ca_ext ]
keyUsage                = critical,keyCertSign,cRLSign
basicConstraints        = critical,CA:true
subjectKeyIdentifier    = hash
authorityKeyIdentifier  = keyid:always

[ signing_req ]
default_bits            = 2048                  
encrypt_key             = yes                  
default_md              = sha256              
utf8                    = yes                
string_mask             = utf8only          
prompt                  = no               
distinguished_name      = signing_ca_dn           
req_extensions          = signing_ca_ext      

[ signing_ca_dn ]
commonName              = $signingca

[ signing_ca_ext ]
keyUsage                = critical,keyCertSign,cRLSign
basicConstraints        = critical,CA:true,pathlen:0
authorityInfoAccess     = @aia_info
crlDistributionPoints   = @crl_info
nameConstraints         = critical,@name_constraints

[ name_constraints ]
permitted;DNS.0=$domain
permitted;URI.0=
permitted;email.0=$domain
excluded;IP.0=0.0.0.0/0.0.0.0
excluded;IP.1=0:0:0:0:0:0:0:0/0:0:0:0:0:0:0:0

[ crl_ext ]
authorityKeyIdentifier  = keyid:always
authorityInfoAccess     = @aia_info

[ aia_info ]
caIssuers;URI.0         = $aia_url

[ crl_info ]
URI.0                   = $crl_url

